[package]
name = "protocol"
version = "0.1.0"
authors = ["Carson Howard <cjhoward92@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bincode = "1.3.1"
serde = "1.0.63"
serde_derive = "1.0.27"